version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    links:
      - db
    volumes:
      - ./src:/go/src/app/src
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12233e23e232e23e
      POSTGRES_USER: postgres
      POSTGRES_DB: auth
    volumes:
      - ./data:/data/db
    ports:
      - '5432:5432'
